### ISSUE TITLE
Camera3d throwing error when rotation X is exactly -90

### ISSUE THREAD

**Issue by RomanPoschl** [indiesoftby/defold-scene3d#23]
**Describe the bug**
Hello when I tried camera3d, it is throwing error when rotation X is exactly -90. I tried to debug it and it looks like Error is in `render3d.lua` . `viewport.view_right` has `vector3` with nan values.

![image](https://user-images.githubusercontent.com/16707031/161401740-c3cc0694-0fed-4d0d-a7ca-890aa8668a55.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/16707031/161401587-fd7982ed-b010-4459-97a1-f0fb06f4c111.png)
4. Run the game

**Expected behavior**
Show sphere

**Hardware (optional)**
 - OS: Windows
 - Version: in project from this URL https://github.com/indiesoftby/defold-scene3d/archive/main.zip

**Additional context (optional)**
Error:
```
ERROR:SCRIPT: scene3d/render/render3d.lua:98: argument #1 contains one or more values which are not numbers: vmath.vector3(nan, nan, nan)
stack traceback:
  [C]:-1: in function cross
  scene3d/render/render3d.lua:98: in function view_direction
  scene3d/camera/camera3d.script:32: in function update_render
  scene3d/camera/camera3d.script:70: in function <scene3d/camera/camera3d.script:68>
```

**Comment by aglitchman** [comment]
Thanks!

Fixed in https://github.com/indiesoftby/defold-scene3d/commit/552a8e1ef94baecba5cd7c7ce7f35f1193596ab0

**Comment by RomanPoschl** [comment]
@aglitchman No problem. I am glad that I can somehow help you. Also, I decided that I will try to create a 3D game so. Probably you can expect more things from me.
